name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout student code
      uses: actions/checkout@v4
    
    - name: Checkout private tests
      uses: actions/checkout@v4
      with:
        repository: Bad-4-Robots/add-two-tests
        token: ${{ secrets.TEST_REPO_PAT }}
        path: tests
    
    - name: List all files
      run: ls -R
    
    - name: Verify Student Submission
      run: |
        if [ ! -f add_numbers.py ]; then
          echo "‚ùå add_numbers.py is missing!"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run Classroom Autograder
      id: test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{ steps.test.outputs.result }}"
      with:
        runners: test
